logging:
  level:
    cn:
      licoy:
        wdog: debug
spring:
  datasource:
    url: jdbc:mysql://122.51.67.240:9036/biz_appot?useUnicode=yes&characterEncoding=UTF8
    username: root
    password: Ds&8&qrzZXxQuJImB&95
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  redis:
    host: 122.51.67.240
    port: 6399
    password: yushangcc
    timeout: 10000
    pool:
      max-active: 10
      min-idle: 3
      max-idle: 5
  thymeleaf:
    cache: false
  aop:
    proxy-target-class: true
    auto: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  #给项目来个名字
  application:
    name: appotmq
  #配置rabbitMq 服务器
  rabbitmq:
    host: 122.51.67.240
    port: 5682
    username: admin
    password: appot2020

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
#  port: 80
  port: 443
  ssl:
    # SSL 证书路径，classpath 必不可少
    key-store: classpath:yushangcc.com.jks
    # SSL 证书密码
    key-store-password: zhongjil11
    # 证书类型
    key-store-type: JKS
    # 证书别名
    key-alias: yushangcc.com
  maxHttpHeaderSize: 10240000
  maxHttpPostSize: 10240000
  tomcat:
    max-threads: 1000
    min-spare-threads: 300
    maxHttpHeaderSize: 10240000
    maxHttpPostSize: 10240000
resources: # 指定静态资源的路径
  static-locations: classpath:/static/,classpath:/views/,classpath:/staticc/
  cache-period: 0

